
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action openAction;

	private global::Gtk.Action saveAction;

	private global::Gtk.Action saveAsAction;

	private global::Gtk.Action aboutAction;

	private global::Gtk.VBox MainVBox;

	private global::Gtk.Toolbar MainToolbar;

	private global::Gtk.Frame RegexFrame;

	private global::Gtk.Alignment GtkAlignment;

	private global::Gtk.VBox RegexFrameVBox;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TextView RegexTextView;

	private global::Gtk.HBox RegexFlagHBox;

	private global::Gtk.CheckButton IgnoreCaseCheckButton;

	private global::Gtk.CheckButton IgnorePatternWhitespaceCheckButton;

	private global::Gtk.Label RegexFrameLabel;

	private global::Gtk.Frame InputFrame;

	private global::Gtk.Alignment GtkAlignment1;

	private global::Gtk.Notebook InputStringNotebook;

	private global::Gtk.ScrolledWindow GtkScrolledWindow3;

	private global::Gtk.TextView SearchInputTextView;

	private global::Gtk.Label SearchInputLabel;

	private global::Gtk.ScrolledWindow GtkScrolledWindow2;

	private global::Gtk.TextView ReplaceInputTextView;

	private global::Gtk.Label ReplaceInputLabel;

	private global::Gtk.Label InputFrameLabel;

	private global::Gtk.Frame ResultFrame;

	private global::Gtk.Alignment GtkAlignment2;

	private global::Gtk.Notebook ResultNotebook;

	private global::Gtk.ScrolledWindow GtkScrolledWindow4;

	private global::Gtk.TreeView GroupResultTreeView;

	private global::Gtk.Label GroupResultLabel;

	private global::Gtk.ScrolledWindow GtkScrolledWindow1;

	private global::Gtk.TextView MatchResultTextView;

	private global::Gtk.Label MatchResultLabel;

	private global::Gtk.ScrolledWindow GtkScrolledWindow5;

	private global::Gtk.TextView ReplaceResultTextView;

	private global::Gtk.Label ReplaceResultLabel;

	private global::Gtk.Label ResultFrameLabel;

	private global::Gtk.Statusbar statusbar1;

	private global::Gtk.Label RegexStatusLabel;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.openAction = new global::Gtk.Action ("openAction", null, null, "gtk-open");
		w1.Add (this.openAction, null);
		this.saveAction = new global::Gtk.Action ("saveAction", null, null, "gtk-save");
		w1.Add (this.saveAction, null);
		this.saveAsAction = new global::Gtk.Action ("saveAsAction", null, null, "gtk-save-as");
		w1.Add (this.saveAsAction, null);
		this.aboutAction = new global::Gtk.Action ("aboutAction", null, null, "gtk-about");
		w1.Add (this.aboutAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("GtkRegexNet");
		this.Icon = global::Gdk.Pixbuf.LoadFromResource ("GtkRegexNet.MainIcon.svg");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.MainVBox = new global::Gtk.VBox ();
		this.MainVBox.Name = "MainVBox";
		this.MainVBox.Spacing = 6;
		// Container child MainVBox.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><toolbar name='MainToolbar'><toolitem name='openAction' action='openAction'/><toolitem name='saveAction' action='saveAction'/><toolitem name='saveAsAction' action='saveAsAction'/><toolitem name='aboutAction' action='aboutAction'/></toolbar></ui>");
		this.MainToolbar = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/MainToolbar")));
		this.MainToolbar.Name = "MainToolbar";
		this.MainToolbar.ShowArrow = false;
		this.MainVBox.Add (this.MainToolbar);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.MainVBox[this.MainToolbar]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child MainVBox.Gtk.Box+BoxChild
		this.RegexFrame = new global::Gtk.Frame ();
		this.RegexFrame.Name = "RegexFrame";
		this.RegexFrame.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child RegexFrame.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment (0f, 0f, 1f, 1f);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.RegexFrameVBox = new global::Gtk.VBox ();
		this.RegexFrameVBox.Name = "RegexFrameVBox";
		this.RegexFrameVBox.Spacing = 6;
		// Container child RegexFrameVBox.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.RegexTextView = new global::Gtk.TextView ();
		this.RegexTextView.CanFocus = true;
		this.RegexTextView.Name = "RegexTextView";
		this.GtkScrolledWindow.Add (this.RegexTextView);
		this.RegexFrameVBox.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.RegexFrameVBox[this.GtkScrolledWindow]));
		w4.Position = 0;
		// Container child RegexFrameVBox.Gtk.Box+BoxChild
		this.RegexFlagHBox = new global::Gtk.HBox ();
		this.RegexFlagHBox.Name = "RegexFlagHBox";
		this.RegexFlagHBox.Spacing = 6;
		// Container child RegexFlagHBox.Gtk.Box+BoxChild
		this.IgnoreCaseCheckButton = new global::Gtk.CheckButton ();
		this.IgnoreCaseCheckButton.CanFocus = true;
		this.IgnoreCaseCheckButton.Name = "IgnoreCaseCheckButton";
		this.IgnoreCaseCheckButton.Label = global::Mono.Unix.Catalog.GetString ("Ignore Case");
		this.IgnoreCaseCheckButton.DrawIndicator = true;
		this.IgnoreCaseCheckButton.UseUnderline = true;
		this.RegexFlagHBox.Add (this.IgnoreCaseCheckButton);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.RegexFlagHBox[this.IgnoreCaseCheckButton]));
		w5.Position = 0;
		// Container child RegexFlagHBox.Gtk.Box+BoxChild
		this.IgnorePatternWhitespaceCheckButton = new global::Gtk.CheckButton ();
		this.IgnorePatternWhitespaceCheckButton.CanFocus = true;
		this.IgnorePatternWhitespaceCheckButton.Name = "IgnorePatternWhitespaceCheckButton";
		this.IgnorePatternWhitespaceCheckButton.Label = global::Mono.Unix.Catalog.GetString ("IgnorePatternWhitespace");
		this.IgnorePatternWhitespaceCheckButton.DrawIndicator = true;
		this.IgnorePatternWhitespaceCheckButton.UseUnderline = true;
		this.RegexFlagHBox.Add (this.IgnorePatternWhitespaceCheckButton);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.RegexFlagHBox[this.IgnorePatternWhitespaceCheckButton]));
		w6.Position = 1;
		this.RegexFrameVBox.Add (this.RegexFlagHBox);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.RegexFrameVBox[this.RegexFlagHBox]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		this.GtkAlignment.Add (this.RegexFrameVBox);
		this.RegexFrame.Add (this.GtkAlignment);
		this.RegexFrameLabel = new global::Gtk.Label ();
		this.RegexFrameLabel.Name = "RegexFrameLabel";
		this.RegexFrameLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Regex</b>");
		this.RegexFrameLabel.UseMarkup = true;
		this.RegexFrame.LabelWidget = this.RegexFrameLabel;
		this.MainVBox.Add (this.RegexFrame);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.MainVBox[this.RegexFrame]));
		w10.Position = 1;
		// Container child MainVBox.Gtk.Box+BoxChild
		this.InputFrame = new global::Gtk.Frame ();
		this.InputFrame.Name = "InputFrame";
		this.InputFrame.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child InputFrame.Gtk.Container+ContainerChild
		this.GtkAlignment1 = new global::Gtk.Alignment (0f, 0f, 1f, 1f);
		this.GtkAlignment1.Name = "GtkAlignment1";
		this.GtkAlignment1.LeftPadding = ((uint)(12));
		// Container child GtkAlignment1.Gtk.Container+ContainerChild
		this.InputStringNotebook = new global::Gtk.Notebook ();
		this.InputStringNotebook.CanFocus = true;
		this.InputStringNotebook.Name = "InputStringNotebook";
		this.InputStringNotebook.CurrentPage = 1;
		// Container child InputStringNotebook.Gtk.Notebook+NotebookChild
		this.GtkScrolledWindow3 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow3.Name = "GtkScrolledWindow3";
		this.GtkScrolledWindow3.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow3.Gtk.Container+ContainerChild
		this.SearchInputTextView = new global::Gtk.TextView ();
		this.SearchInputTextView.CanFocus = true;
		this.SearchInputTextView.Name = "SearchInputTextView";
		this.GtkScrolledWindow3.Add (this.SearchInputTextView);
		this.InputStringNotebook.Add (this.GtkScrolledWindow3);
		// Notebook tab
		this.SearchInputLabel = new global::Gtk.Label ();
		this.SearchInputLabel.Name = "SearchInputLabel";
		this.SearchInputLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Search");
		this.InputStringNotebook.SetTabLabel (this.GtkScrolledWindow3, this.SearchInputLabel);
		this.SearchInputLabel.ShowAll ();
		// Container child InputStringNotebook.Gtk.Notebook+NotebookChild
		this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
		this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
		this.ReplaceInputTextView = new global::Gtk.TextView ();
		this.ReplaceInputTextView.CanFocus = true;
		this.ReplaceInputTextView.Name = "ReplaceInputTextView";
		this.GtkScrolledWindow2.Add (this.ReplaceInputTextView);
		this.InputStringNotebook.Add (this.GtkScrolledWindow2);
		global::Gtk.Notebook.NotebookChild w14 = ((global::Gtk.Notebook.NotebookChild)(this.InputStringNotebook[this.GtkScrolledWindow2]));
		w14.Position = 1;
		// Notebook tab
		this.ReplaceInputLabel = new global::Gtk.Label ();
		this.ReplaceInputLabel.Name = "ReplaceInputLabel";
		this.ReplaceInputLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Replace");
		this.InputStringNotebook.SetTabLabel (this.GtkScrolledWindow2, this.ReplaceInputLabel);
		this.ReplaceInputLabel.ShowAll ();
		this.GtkAlignment1.Add (this.InputStringNotebook);
		this.InputFrame.Add (this.GtkAlignment1);
		this.InputFrameLabel = new global::Gtk.Label ();
		this.InputFrameLabel.Name = "InputFrameLabel";
		this.InputFrameLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Input String</b>");
		this.InputFrameLabel.UseMarkup = true;
		this.InputFrame.LabelWidget = this.InputFrameLabel;
		this.MainVBox.Add (this.InputFrame);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.MainVBox[this.InputFrame]));
		w17.Position = 2;
		// Container child MainVBox.Gtk.Box+BoxChild
		this.ResultFrame = new global::Gtk.Frame ();
		this.ResultFrame.Name = "ResultFrame";
		this.ResultFrame.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child ResultFrame.Gtk.Container+ContainerChild
		this.GtkAlignment2 = new global::Gtk.Alignment (0f, 0f, 1f, 1f);
		this.GtkAlignment2.Name = "GtkAlignment2";
		this.GtkAlignment2.LeftPadding = ((uint)(12));
		// Container child GtkAlignment2.Gtk.Container+ContainerChild
		this.ResultNotebook = new global::Gtk.Notebook ();
		this.ResultNotebook.CanFocus = true;
		this.ResultNotebook.Name = "ResultNotebook";
		this.ResultNotebook.CurrentPage = 2;
		// Container child ResultNotebook.Gtk.Notebook+NotebookChild
		this.GtkScrolledWindow4 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow4.Name = "GtkScrolledWindow4";
		this.GtkScrolledWindow4.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow4.Gtk.Container+ContainerChild
		this.GroupResultTreeView = new global::Gtk.TreeView ();
		this.GroupResultTreeView.CanFocus = true;
		this.GroupResultTreeView.Name = "GroupResultTreeView";
		this.GtkScrolledWindow4.Add (this.GroupResultTreeView);
		this.ResultNotebook.Add (this.GtkScrolledWindow4);
		// Notebook tab
		this.GroupResultLabel = new global::Gtk.Label ();
		this.GroupResultLabel.Name = "GroupResultLabel";
		this.GroupResultLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Group");
		this.ResultNotebook.SetTabLabel (this.GtkScrolledWindow4, this.GroupResultLabel);
		this.GroupResultLabel.ShowAll ();
		// Container child ResultNotebook.Gtk.Notebook+NotebookChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.MatchResultTextView = new global::Gtk.TextView ();
		this.MatchResultTextView.CanFocus = true;
		this.MatchResultTextView.Name = "MatchResultTextView";
		this.MatchResultTextView.Editable = false;
		this.MatchResultTextView.CursorVisible = false;
		this.GtkScrolledWindow1.Add (this.MatchResultTextView);
		this.ResultNotebook.Add (this.GtkScrolledWindow1);
		global::Gtk.Notebook.NotebookChild w21 = ((global::Gtk.Notebook.NotebookChild)(this.ResultNotebook[this.GtkScrolledWindow1]));
		w21.Position = 1;
		// Notebook tab
		this.MatchResultLabel = new global::Gtk.Label ();
		this.MatchResultLabel.Name = "MatchResultLabel";
		this.MatchResultLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Match");
		this.ResultNotebook.SetTabLabel (this.GtkScrolledWindow1, this.MatchResultLabel);
		this.MatchResultLabel.ShowAll ();
		// Container child ResultNotebook.Gtk.Notebook+NotebookChild
		this.GtkScrolledWindow5 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow5.Name = "GtkScrolledWindow5";
		this.GtkScrolledWindow5.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow5.Gtk.Container+ContainerChild
		this.ReplaceResultTextView = new global::Gtk.TextView ();
		this.ReplaceResultTextView.CanFocus = true;
		this.ReplaceResultTextView.Name = "ReplaceResultTextView";
		this.ReplaceResultTextView.Editable = false;
		this.ReplaceResultTextView.CursorVisible = false;
		this.GtkScrolledWindow5.Add (this.ReplaceResultTextView);
		this.ResultNotebook.Add (this.GtkScrolledWindow5);
		global::Gtk.Notebook.NotebookChild w23 = ((global::Gtk.Notebook.NotebookChild)(this.ResultNotebook[this.GtkScrolledWindow5]));
		w23.Position = 2;
		// Notebook tab
		this.ReplaceResultLabel = new global::Gtk.Label ();
		this.ReplaceResultLabel.Name = "ReplaceResultLabel";
		this.ReplaceResultLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Replace");
		this.ResultNotebook.SetTabLabel (this.GtkScrolledWindow5, this.ReplaceResultLabel);
		this.ReplaceResultLabel.ShowAll ();
		this.GtkAlignment2.Add (this.ResultNotebook);
		this.ResultFrame.Add (this.GtkAlignment2);
		this.ResultFrameLabel = new global::Gtk.Label ();
		this.ResultFrameLabel.Name = "ResultFrameLabel";
		this.ResultFrameLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Result</b>");
		this.ResultFrameLabel.UseMarkup = true;
		this.ResultFrame.LabelWidget = this.ResultFrameLabel;
		this.MainVBox.Add (this.ResultFrame);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.MainVBox[this.ResultFrame]));
		w26.Position = 3;
		// Container child MainVBox.Gtk.Box+BoxChild
		this.statusbar1 = new global::Gtk.Statusbar ();
		this.statusbar1.Name = "statusbar1";
		this.statusbar1.Spacing = 6;
		// Container child statusbar1.Gtk.Box+BoxChild
		this.RegexStatusLabel = new global::Gtk.Label ();
		this.RegexStatusLabel.Name = "RegexStatusLabel";
		this.RegexStatusLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Regex: Unkown");
		this.statusbar1.Add (this.RegexStatusLabel);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.statusbar1[this.RegexStatusLabel]));
		w27.Position = 1;
		w27.Expand = false;
		w27.Fill = false;
		this.MainVBox.Add (this.statusbar1);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.MainVBox[this.statusbar1]));
		w28.Position = 4;
		w28.Expand = false;
		w28.Fill = false;
		this.Add (this.MainVBox);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 470;
		this.DefaultHeight = 538;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.openAction.Activated += new global::System.EventHandler (this.OpenActivatedEvent);
		this.saveAsAction.Activated += new global::System.EventHandler (this.SaveAsActivatedEvent);
		this.aboutAction.Activated += new global::System.EventHandler (this.AboutActivatedEvent);
		this.IgnoreCaseCheckButton.Toggled += new global::System.EventHandler (this.IgnoreCaseToggledEvent);
		this.IgnorePatternWhitespaceCheckButton.Toggled += new global::System.EventHandler (this.IgnorePatternWhitespaceToggledEvent);
	}
}
